py train_mlp.py --train_file data/higgs.train --batch_size 1
py train_mlp.py --train_file data/higgs.train --batch_size 2
py train_mlp.py --train_file data/higgs.train --batch_size 3 
py train_mlp.py --train_file data/higgs.train --batch_size 4 
py train_mlp.py --train_file data/higgs.train --batch_size 5 
py train_mlp.py --train_file data/higgs.train --batch_size 6
py train_mlp.py --train_file data/higgs.train --batch_size 7 
py train_mlp.py --train_file data/higgs.train --batch_size 8 
py train_mlp.py --train_file data/higgs.train --batch_size 9 
py train_mlp.py --train_file data/higgs.train --batch_size 10 
py train_mlp.py --train_file data/higgs.train --batch_size 11
py train_mlp.py --train_file data/higgs.train --batch_size 12 
py train_mlp.py --train_file data/higgs.train --batch_size 13
py train_mlp.py --train_file data/higgs.train --batch_size 14 
py train_mlp.py --train_file data/higgs.train --batch_size 15
py train_mlp.py --train_file data/higgs.train --batch_size 16 
py train_mlp.py --train_file data/higgs.train --batch_size 17
py train_mlp.py --train_file data/higgs.train --batch_size 18 
py train_mlp.py --train_file data/higgs.train --batch_size 19
py train_mlp.py --train_file data/higgs.train --batch_size 20
